
#FROM debian:testing
#FROM debian:unstable
FROM debian:stable

LABEL maintainer="http://www.halclark.ca" \
      description="An EGSnrc appliance."

#EXPOSE 80
#EXPOSE 443

WORKDIR /scratch
ADD . /scratch


# Install core build dependencies.
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get --yes update && \
    apt-get --yes install \
      git \
      make \
      cmake \
      g++ \
      gcc \
      gfortran \
      vim \
      gdb \
      rsync


# Install other dependencies.
RUN apt-get install --yes \
    ` # EGSnrc dependencies. ` \
        tcl \
        tk \
        grace \
        libmotif-dev \
        qt5-default \
        qt5-qmake \
        at \
        expect \
        imagej \
        kate \
    ` # Misc.` \
        htcondor \
    ` # Software X server that provides OpenGL extensions.` \
        x-window-system \
        mesa-utils \
        xserver-xorg-video-dummy \
        x11-apps


# Needed for the software X server.
RUN mv xpra-xorg.conf /etc/X11/xorg.conf


# Source and configure EGSnrc.
WORKDIR /egsnrc
RUN git clone --progress https://github.com/nrc-cnrc/EGSnrc.git . && \
    ./HEN_HOUSE/scripts/configure.expect linux.conf 1
ENV EGS_HOME "/egsnrc/egs_home/"
ENV EGS_CONFIG "/egsnrc/HEN_HOUSE/specs/linux.conf"
#ENV HEN_HOUSE "/egsnrc/HEN_HOUSE/"
RUN . /egsnrc/HEN_HOUSE/scripts/egsnrc_bashrc_additions
RUN printf '. /egsnrc/HEN_HOUSE/scripts/egsnrc_bashrc_additions\n' >> /etc/profile
RUN printf '. /egsnrc/HEN_HOUSE/scripts/egsnrc_bashrc_additions\n' >> /etc/bash.bashrc
RUN printf '. /egsnrc/HEN_HOUSE/scripts/egsnrc_bashrc_additions\n' >> /root/.bashrc


# Build the GUI tools.
ENV QTDIR "/usr"
RUN cd /egsnrc/HEN_HOUSE/gui/        && make -j $(nproc) --print-directory && \
    cd /egsnrc/HEN_HOUSE/egs++/view/ && make -j $(nproc) --print-directory


# Run the EGSnrc test script.
RUN test_distribution


# Default to launching the run script.
#WORKDIR /egsnrc/egs_home
WORKDIR /working
CMD ["/bin/bash", "/scratch/Run_Default_Simulation.sh"]

